import { Poppins, Geist_Mono } from "next/font/google";
import "./globals.css";

// Usando Poppins (definindo o peso como 400, mas você pode ajustar conforme necessário)
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500"], // Defina o peso desejado aqui
});

// Usando Geist_Mono (Fonte monoespaçada)
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: ["400"], // Se quiser um peso específico para Geist_Mono
});

export const metadata = {
  title: "Victor.dev",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
